import 'package:get/get_navigation/get_navigation.dart';

class MyLocalization implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'login': 'تسجيل الدخول',
          "don't_have_an_account": 'ليس لديك حساب ؟',
          'sign_up': 'تسجيل حساب جديد',
          "this_email_is_not_valid": 'هذا الحساب ليس صحيحا',
          "password_message_wrong":
              'كلمة المرور قصير جدا , يجب ان لا تقل عن 7 أحرف',
          "name_message_wrong": 'الاسم قصير جداً',
          'not_valid': 'ليس صحيحاً',
          'something_error': 'حدث خطأ ما !',
          'no_tasks': 'لا يوجد مهام!',
          'Please_choose_an_image': 'من فضلك اختار صورة',
          'please_select_profile_image': 'من فضلك اختر صورة لملفك الشخصي',
          'weak_password': 'كلمة المرور ضعيفة',
          'email_already_in_use': 'هذا الحساب مستخدم من قبل',
          'camera': 'الكاميرا',
          'gallery': 'معرض الصور',
          'warning': 'تحذير',
          'email': 'البريد الالكتروني',
          'password': 'كلمة المرور',
          'forget_password': 'نسيت كلمة السر؟',
          'reset_password': 'اعادة تعيين كلمة المرور',
          'already_have_an_account': 'لديك حساب بالفعل ؟',
          'please_select_an_image': 'من فضلك اختر صوره',
          'full_name': 'الاسم بالكامل',
          'phone_number': 'رقم الهاتف',
          'company_position': 'الوظيفة',
          'tasks': 'المهام',
          'task_category': 'فئة المهمه',
          'cancel': 'خروج',
          'cancel2': 'رجوع',
          'cancel_filter': 'الغاء الشرط',
          'all_tasks': 'جميع المهام',
          'my_account': 'حسابي',
          'register_workers': 'الموظفين',
          'add_task': 'إضافة مهمه جديدة',
          'log_out': 'تسجيل الخروج',
          'contact_info': 'معلومات التواصل👇',
          'confirm': 'اختر',
          'all_workers': 'جميع الموظفين',
          'task_title': 'اسم المهمه',
          'task_description': 'وصف المهمه',
          'deadline_date': 'تاريخ الانتهاء',
          'upload': 'تحميل المهمه',
          'upload_by': 'تم وضع المهمه بواسطة',
          'upload_on': 'تاريخ البدأ',
          'done_status': 'الحالة',
          'done': 'أكتمل',
          'add_comment': 'اضافة تعليق',
          'comment': 'تعليق',
          'post': 'نشر',
          'all_filed_are_required': 'جميع الحقول مهمه',
          'business': 'عمل',
          'programming': 'برمجة',
          'information_technology': 'تكنولوجيا المعلومات',
          'human_resources': 'الموارد البشرية',
          'marketing': 'تسويق',
          'design': 'تصميم',
          'accounting': 'محاسبة',
          "pick_up_date": 'من فضلك اختر تاريخ',
          'do_you_want_sign_out': 'هل تريد تسجيل الخروج ؟',
          'develop_an_app': 'التطبيق تحت التطوير',
          "validator": 'هناك خطأ , لا يجب ان يقل عدد الحروف عن 7 ',
          'success': 'تم بنجاح ✅',
          'uploaed_task_suceesfully': 'تم رفع إضافه المهمه بنجاح',
          'please_select_date': 'من فضلك اختر تاريخ',
          'remove': 'حذف',
          'change_lan': 'تغير اللغة',
          'you_can_not_delete_this_task':
              'عذرا , فانت لا تملك صلاحية حذف هذه المهمه',
          'no_user_found_for_that_email': 'عذرا لا يوجد مستخدم بهذا الحساب',
          'wrong_password_provided_for_that_user': 'كلمة المرور ليست صحيحه',
          'change_theme': 'تغير الثيم',
          'chats_screen': 'المحادثات',
          'message': 'اكتب رسالتك',
          'something_wrong': 'هناك شي ما خطأ',
        },
        'en': {
          'uploaed_task_suceesfully': 'Uploaed Task Suceesfully',
          'change_lan': 'Change Language',
          'login': 'Login ',
          "don't_have_an_account": "Don't have an account? ",
          'something_error': 'Something Error!',
          'sign_up': 'Sign Up',
          'success': 'Success✅',
          'remove': 'Remove',
          'confirm': 'Confirm',
          'you_can_not_delete_this_task': 'You can\'t delete this task!',
          'email': 'Email Address',
          'no_tasks': 'There are no tasks',
          'password': 'Password',
          "name_message_wrong": 'This name is too short',
          "this_email_is_not_valid": 'This Email is Not Valid',
          "password_message_wrong":
              'This Password it too short , it should at least 7 letters ',
          "validator": 'This Filed is missing ,it should at least 7 letters ',
          'not_valid': 'Not Valid',
          'forget_password': 'Forget Password?',
          'reset_password': 'Reset Password',
          'already_have_an_account': "Aleady have an account",
          'weak_password': 'The password provided is too weak.',
          'email_already_in_use': 'Email Already In Use',
          'full_name': 'Full Name',
          'phone_number': 'Phone Number',
          'company_position': 'Company Position',
          'Please_choose_an_image': 'Please Choose an Image',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'warning': 'Warning',
          'please_select_an_image': 'Please Select an Image',
          'please_select_profile_image': 'Please Select Profile Image',
          'please_select_date': 'Please Select a Date',
          'tasks': 'Tasks',
          'task_category': 'Task Category',
          'cancel': 'Cancel',
          'cancel2': 'Cancel',
          'cancel_filter': 'Cancel Filter',
          'all_tasks': 'All Tasks',
          'my_account': 'My Account',
          'register_workers': 'Register Workers',
          'add_task': 'Add Task',
          'log_out': 'LogOut',
          'contact_info': 'Contact Info👇',
          'all_workers': 'All Workers',
          'task_title': 'Task Title',
          'task_description': 'Task Description',
          'deadline_date': 'Deadline Date',
          'upload': 'Upload',
          'upload_by': 'Uploaded By',
          'upload_on': 'Uploaded On',
          'done_status': 'Done Status',
          'done': 'Done',
          'add_comment': 'Add Comment',
          'post': 'Post',
          'all_filed_are_required': 'All Fileds Are Required',
          'business': 'Business',
          'programming': 'Programming',
          'information_technology': 'Information Technology',
          'human_resources': 'Human Resources',
          'marketing': 'Marketing',
          'design': 'Design',
          'accounting': 'Accounting',
          "pick_up_date": 'Pick up a date',
          'do_you_want_sign_out': 'Do you want to Sign Out?',
          'develop_an_app': 'Develop an App',
          'no_user_found_for_that_email': 'No user found for that email.',
          'change_theme': 'Change Theme',
          'wrong_password_provided_for_that_user':
              'Wrong password provided for that user.',
          'chats_screen': 'Chats',
          'message': 'Message...',
          'something_wrong': 'Something wrong',
        },
      };
}
